### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by wiktor-k** [whitfin/retainer#11]
Hi,

I've just found your crate and it looks ideal for my case.

I had a couple of ideas when browsing docs.rs which you may or may not like (that's why I'm not submitting a PR, unless you do like them ;) )

1. Using `#![doc = include_str!("../README.md")]` in `lib.rs` (an [example here](https://github.com/wiktor-k/testresult/blob/main/src/lib.rs#L1)). That'd embed the README.md file as crate root level documentation. It has two nice properties: first the docs.rs page has content with code examples instead of short info: https://docs.rs/retainer/0.3.0/retainer/ second it makes cargo test run the examples in your README thus making sure they are OK.

2. Instead of having this snippet of code:

```toml
[dependencies]
retainer = "0.3"
```

Ask users to execute `cargo add retainer` which will always pick-up the latest version and you wouldn't have to update the README on each release.

Well... that's it for now. Thanks for such a great crate! :wave:

**Comment by whitfin** [comment]
Hi! 

Thanks for the suggestions - if you want to PR them I'd gladly accept them! I think `cargo add` wasn't around officially when I first wrote this, it's definitely much better.

Thank you for the kind words too 🙌
