### ISSUE TITLE
Feature: Expose iterator to underlying store

### ISSUE THREAD

**Issue by thrykol** [whitfin/retainer#4]
I have a use case where I have small collection who's data needs to expire.  Retainer would work well for me except that there's not a way for me to access the underlying map without knowing the individual keys in the map.

**Comment by whitfin** [comment]
The issue with this is that it requires locking the entire cache (and delaying eviction) for the entire lifetime of the `Iterator`, so it's not really something to encourage. I can take a look at options, but when I first wrote this I decided to leave it out for this reason.
