### ISSUE TITLE
Feature: get() function that returns expiration info?

### ISSUE THREAD

**Issue by nickbp** [whitfin/retainer#6]
I'm attempting to `get()` a value while also seeing how long it has left until it expires. It looks like right now the `CacheEntryReadGuard` returned by `get()` only returns the value.

The equivalent of this in Redis is a script like the following that can be run as a single query:
```
return {redis.call('get',KEYS[1]), redis.call('ttl',KEYS[1])}
```

As of 0.2.2 a workaround is to `remove()` the value (getting the full `CacheEntry`) and then putting the value back with an `insert()` against the original expiration deadline.

A couple possible ways of doing this (haven't looked at the internals so don't know which makes more sense):
- An alternative `get()` function that returns the `CacheEntry`, including the expiration time, rather than just the `CacheEntryReadGuard` that only includes the value?
- Add the expiration field to `CacheEntryReadGuard`?

**Comment by whitfin** [comment]
Conversation regarding this has taken place inside the linked PR.
